import pygame
import numpy as np
from pygame.locals import QUIT, KEYDOWN, K_ESCAPE

WIDTH, HEIGHT = 800, 800
EARTH_RADIUS = 6371e3
HURRICANE_ROTATION_SPEED = 5
VISUAL_SCALE = 1e-5
HURRICANE_INITIAL_RADIUS = 